export const INITIAL_PROBLEMS = [
  {
    id: '1',
    title: 'Two Sum',
    topic: 'Arrays',
    difficulty: 'Easy',
    company: 'Google',
    confidence: 5,
    status: 'Solved',
    attempts: 2,
    notes: 'Use a hash map for O(n) lookup. Key insight: store complement as you iterate.',
    dateAdded: '2024-01-10',
  },
  {
    id: '2',
    title: 'Longest Substring Without Repeating Characters',
    topic: 'Sliding Window',
    difficulty: 'Medium',
    company: 'Amazon',
    confidence: 3,
    status: 'Solved',
    attempts: 4,
    notes: 'Sliding window with a set. Expand right, shrink left when duplicate found.',
    dateAdded: '2024-01-12',
  },
  {
    id: '3',
    title: 'Binary Tree Level Order Traversal',
    topic: 'Trees',
    difficulty: 'Medium',
    company: 'Meta',
    confidence: 2,
    status: 'Attempted',
    attempts: 3,
    notes: 'BFS with a queue. Push left then right child at each level.',
    dateAdded: '2024-01-15',
  },
  {
    id: '4',
    title: 'Merge K Sorted Lists',
    topic: 'Heaps',
    difficulty: 'Hard',
    company: 'Microsoft',
    confidence: 1,
    status: 'Attempted',
    attempts: 1,
    notes: 'Use a min-heap. Still shaky on the implementation.',
    dateAdded: '2024-01-18',
  },
  {
    id: '5',
    title: 'Coin Change',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    company: 'Apple',
    confidence: 4,
    status: 'Solved',
    attempts: 2,
    notes: 'Bottom-up DP. dp[i] = min coins to make amount i.',
    dateAdded: '2024-01-20',
  },
  {
    id: '6',
    title: 'Number of Islands',
    topic: 'Graphs',
    difficulty: 'Medium',
    company: 'Google',
    confidence: 3,
    status: 'Solved',
    attempts: 2,
    notes: 'DFS to mark visited cells. Count number of DFS calls.',
    dateAdded: '2024-01-22',
  },
  {
    id: '7',
    title: 'Valid Parentheses',
    topic: 'Stacks',
    difficulty: 'Easy',
    company: 'Netflix',
    confidence: 5,
    status: 'Solved',
    attempts: 1,
    notes: 'Push open brackets, pop and check on close brackets.',
    dateAdded: '2024-01-24',
  },
  {
    id: '8',
    title: 'Word Ladder',
    topic: 'BFS',
    difficulty: 'Hard',
    company: 'Amazon',
    confidence: 1,
    status: 'Not Started',
    attempts: 0,
    notes: '',
    dateAdded: '2024-01-26',
  },
  {
    id: '9',
    title: 'Maximum Subarray',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    company: 'Microsoft',
    confidence: 4,
    status: 'Solved',
    attempts: 2,
    notes: "Kadane's algorithm. Track current sum and max sum.",
    dateAdded: '2024-01-28',
  },
  {
    id: '10',
    title: 'Binary Search',
    topic: 'Binary Search',
    difficulty: 'Easy',
    company: 'Google',
    confidence: 5,
    status: 'Solved',
    attempts: 1,
    notes: 'Classic left/right pointer. Watch out for mid overflow.',
    dateAdded: '2024-01-30',
  },
  {
    id: '11',
    title: 'LRU Cache',
    topic: 'Design',
    difficulty: 'Medium',
    company: 'Meta',
    confidence: 2,
    status: 'Attempted',
    attempts: 3,
    notes: 'Use a doubly linked list + hashmap combo.',
    dateAdded: '2024-02-01',
  },
  {
    id: '12',
    title: 'Trapping Rain Water',
    topic: 'Arrays',
    difficulty: 'Hard',
    company: 'Amazon',
    confidence: 2,
    status: 'Attempted',
    attempts: 2,
    notes: 'Two pointer approach. Track max from left and right.',
    dateAdded: '2024-02-03',
  },
];

export const TOPICS = [
  'Arrays', 'Strings', 'Trees', 'Graphs', 'Dynamic Programming',
  'Sliding Window', 'Stacks', 'Heaps', 'BFS', 'DFS',
  'Binary Search', 'Recursion', 'Design', 'Backtracking',
];

export const COMPANIES = [
  'Google', 'Amazon', 'Meta', 'Microsoft', 'Apple',
  'Netflix', 'Uber', 'Stripe', 'Other',
];

export const DIFFICULTIES = ['Easy', 'Medium', 'Hard'];
export const STATUSES = ['Solved', 'Attempted', 'Not Started'];
